<a href="https://colab.research.google.com/github/theluckiestsoul/ml/blob/main/Vectors_%26_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Creating vectors
# Avector is just a list of numbers and a matrixs is a table of numbers.
# ML algorithms use vector for single data points and matrices for data points.

v1 = np.array([2,3])
v2 = np.array([4,5])


print("v1= ",v1)
print("v2= ",v2)

# Dot product
# Dot products tells us how similar two vectors are

dot_value = np.dot(v1,v2)
print("Dot products of two v1, v2 are =",dot_value)

# Creating metrices
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

C = A.dot(B)
print("A × B =\n", C)

# Transpose . it flips rows and columns
print("A Transpose:\n",A.T)

# Representing a dataset in matrix
# Each row is one example and each column is one feature
X =np.array([[25,50000],
             [30,60000],
             [35,70000]
             ])

print("Dataset matrix:\n",X)
print("Shape \n",X.shape)


v1=  [2 3]
v2=  [4 5]
Dot products of two v1, v2 are = 23
Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[1 2]
 [3 4]
 [5 6]]
A × B =
 [[22 28]
 [49 64]]
A Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Dataset matrix:
 [[   25 50000]
 [   30 60000]
 [   35 70000]]
Shape 
 (3, 2)


In [ ]:
import numpy as np


# Exercise

## Compute dot product of [1,2,3] and [4,5,6]
m1 = np.array([1,2,3])
m2 = np.array([4,5,6])

print("Dot product of (m1,m2)",m1.dot(m2))

Dot product of (m1,m2) 32


In [ ]:
# Multiple a 3x3 matrix with a 3x1 matrix

import numpy as np


m1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

m2 = np.array([
    [1],
    [2],
    [3]
])

# formula of matrix multiplication
# A[i,j], B[i,j]=A[i]*B[j]
# (A is m x n) x (B is n x p ) =(m x p)

print(m1.dot(m2))

[[14]
 [32]
 [50]]


In [ ]:
# (c) Create a dataset matrix of 5 students with 3 scores each.

import numpy as np

# Create a dataset matrix of 5 students with 3 scores each
# Each row represents. a student, and each column reperesents  a score
dataset_matrix= np.array([[76,78,90],
                          [77,89,90],
                          [68,90,67],
                          [99,99,99],
                          [97,80,90]
                          ])

print(dataset_matrix)
print("Shape of the matrix",dataset_matrix.shape)




[[76 78 90]
 [77 89 90]
 [68 90 67]
 [99 99 99]
 [97 80 90]]
Shape of the matrix (5, 3)


#